services:
  mysql:
    image: mysql:8.0
    container_name: jobportal-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jobportal_db
      MYSQL_USER: jobportal_user
      MYSQL_PASSWORD: jobportal_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jobportal-network

volumes:
  mysql_data:
    driver: local

networks:
  jobportal-network:
    driver: bridge
